name: Deploy PHP App

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          
      - name: Test SSH access 一定要留下來檢查有沒有過
        run: |
          ssh -i ~/.ssh/id_rsa \
            -o StrictHostKeyChecking=no \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "ls -la /home/${{ secrets.SSH_USER }} && echo 'SSH access success'"
      
      - name: Ensure deploy directory exists
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ~/php-game"
      
          
      
      - name: Upload project with vendor
        run: |
          scp -i ~/.ssh/id_rsa -r \
            Dockerfile \
            docker-compose.yml \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/php-game/
            

            

      - name: Deploy on VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd ~/php-game &&
            docker build -t php-game . &&
            docker stop TABALL || true &&
            docker rm TABALL || true &&
            docker run -d --name TABALL -p 80:80  php-game
          '
