name: Deploy PHP App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: 2. 注入生產環境 config.php 檔案
        run: |
          echo "${{ secrets.PHP_CONFIG }}" > config.php
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader


      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Ensure deploy directory exists
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ~/php-app"

      - name: Upload project with vendor
        run: |
          scp -i ~/.ssh/id_rsa -r \
            composer.json \
            composer.lock \
            vendor \
            src \
            Dockerfile \
            config.php \
            .htaccess \
            docker-compose.yml \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/php-game/
            

            

      - name: Deploy on VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd ~/php-game &&
            docker build -t my-php-app . &&
            docker stop php-container || true &&
            docker rm php-container || true &&
            docker run -d --name php-container -p 80:80 my-php-app
          '
